### ISSUE TITLE
Prepare and upload GP "skeleton"

### ISSUE THREAD

**Issue by caranha** [Jace7Valentine/DirectedResearch#2]
Write a test GP program using ECJ, solving a trivial problem (for instance, "XOR" of two variables), and upload it to github.

Write down any difficulties you had during the process of installing ECJ, creating the program, and running the GP.

**Comment by Jace7Valentine** [comment]
Following this [tutorial](https://cs.gmu.edu/~eclab/projects/ecj/docs/tutorials/tutorial4/index.html) I used GP to find the best solution to a multi-valued regression problem (X*X*Y + X*Y + Y*Y). The result [out.stat.txt](https://github.com/Jace7Valentine/DirectedResearch/files/591165/out.stat.txt) was created.

Difficulties & Concerns: 
- I had some trouble getting all the parameter files into the correct directory. The files were originally inside the ECJ.jar file, which I could not access, so I decided to copy them into the main project directory. 
- I do not fully understand the parameter files, because I do not know enough about GP. I will continue to read my book on GP to wrap my head around all the parameters. 
- Lastly, a minor concern, I do not know how to share my run configuration onto github in a meaningful way. The way ECJ GP programs are run is by calling ECJ's Evolve class and passing it your parameter file. ex: `java ec.Evolve -file ParamFile.params`

**Comment by caranha** [comment]
> I do not fully understand the parameter files, because I do not know enough about GP. I will continue to read my book on GP to wrap my head around all the parameters.

Some suggestions:

* Create a new issue and assign it to me, listing the parameters you
don't understant. I'll be happy to explain the ones I know.
* Bring them to our Friday meeting
* Ask in the ECJ mailing list

> Lastly, a minor concern, I do not know how to share my run configuration onto github in a meaningful way. The way ECJ GP programs are run is by calling ECJ's Evolve class and passing it your parameter file. ex: java ec.Evolve -file ParamFile.params

Is the parameter file a java file or a plain text file (xml, etc?) if
the later, you can just add a directory for it. If the former, maybe
you can change the object creator to load the parameters from a text
file, and upload the new java file and the appropriate text file to
the repository. Please give me a refresher of how ECJ works this
Friday, I do not remember it being that complicated :-)

Cheers!
